"use client";

import { motion } from "framer-motion";
import { Scale, AlertCircle, FileCheck, ShieldAlert } from "lucide-react";
import Link from "next/link";

export default function TermsOfService() {
  return (
    <div className="min-h-screen pt-24 pb-16 px-6 bg-[#0a0a0a]">
      <div className="max-w-4xl mx-auto">
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-12"
        >
          <Link href="/" className="text-[#3b82f6] text-sm hover:underline mb-4 inline-block">← Back to Home</Link>
          <h1 className="text-4xl font-extrabold text-white mb-4">Terms of Service</h1>
          <p className="text-gray-400">Effective Date: April 8, 2026</p>
        </motion.div>

        <div className="space-y-12">
          {/* Important Notice */}
          <section className="bg-amber-500/5 border border-amber-500/20 p-6 rounded-2xl flex gap-4 items-start">
            <AlertCircle className="w-6 h-6 text-amber-500 flex-shrink-0 mt-1" />
            <div>
              <h2 className="text-lg font-bold text-amber-500 mb-2">Notice to Users</h2>
              <p className="text-sm text-gray-400 leading-relaxed">
                FairAI Studio is an AI auditing and diagnostic tool. By using this service, you acknowledge that the audit results and mitigation suggestions are for informational purposes and do not constitute legal advice or a guarantee of absolute model fairness.
              </p>
            </div>
          </section>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="glass-panel p-6 border-white/5">
              <Scale className="w-8 h-8 text-[#3b82f6] mb-4" />
              <h3 className="text-white font-bold mb-2">Platform Responsibility</h3>
              <p className="text-sm text-gray-400">The platform is provided "as-is" without warranty. We do not guarantee 100% accuracy in bias detection due to the complex nature of algorithmic fairness.</p>
            </div>
            <div className="glass-panel p-6 border-white/5">
              <FileCheck className="w-8 h-8 text-emerald-400 mb-4" />
              <h3 className="text-white font-bold mb-2">User Responsibility</h3>
              <p className="text-sm text-gray-400">Users are solely responsible for the data they upload and any business decisions made based on the audit reports generated by FairAI Studio.</p>
            </div>
          </div>

          <section className="prose prose-invert max-w-none text-gray-400 space-y-8">
            <div>
              <h3 className="text-white text-xl font-bold mb-4">1. Acceptance of Terms</h3>
              <p>
                By accessing or using FairAI Studio, you agree to be bound by these Terms of Service. If you do not agree, please do not use our platform.
              </p>
            </div>

            <div>
              <h3 className="text-white text-xl font-bold mb-4">2. Permitted Use</h3>
              <p>
                FairAI Studio is intended for ethical AI research, model auditing, and compliance checking. You may not use the platform for:
              </p>
              <ul className="list-disc pl-6 space-y-2 mt-4">
                <li>Reverse engineering AI models without authorization.</li>
                <li>Processing sensitive personal data in violation of GDPR or local laws.</li>
                <li>Maliciously exploiting the bias detection system to bypass safety filters.</li>
              </ul>
            </div>

            <div>
              <h3 className="text-white text-xl font-bold mb-4">3. Limitation of Liability</h3>
              <p className="p-4 bg-white/5 rounded-xl border border-white/10 italic">
                "In no event shall FairAI Studio or its contributors be liable for any direct, indirect, incidental, or consequential damages arising out of the use or inability to use the platform, including but not limited to financial loss or regulatory penalties."
              </p>
            </div>

            <div>
              <h3 className="text-white text-xl font-bold mb-4">4. Open Source & Contributions</h3>
              <p>
                Portions of FairAI Studio are open-source. While the core platform is provided for free, individual usage limits may apply to ensure service stability for all users.
              </p>
            </div>
          </section>
        </div>

        <div className="mt-16 pt-8 border-t border-white/5 text-center">
          <p className="text-sm text-gray-500">
            Questions regarding these terms? Contact <a href="mailto:fairaistudio@gmail.com" className="text-[#3b82f6] hover:underline">fairaistudio@gmail.com</a>
          </p>
        </div>
      </div>
    </div>
  );
}
